import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import Ajv from 'ajv/dist/2020.js';
import {evaluateServicePlan as check,payloadDigest} from '../skills/woia-customer-service/scripts/service-plan.mjs';
function fixture(action='external-send') {
 const p={action,operation_id:'operation-a',purpose:'approved-status',organization_id:'org-a',resource_version:'version-3',recipient:{id:'person-a',organization_id:'org-a',classification:'external-person'},payload:{content:'Accepted status'}};
 const c={actor_id:'executor-a',authenticated:true,work_department:'customer-service',organization_id:'org-a',recipient_verified:true,sources:[{ref:'source-1',version:'3',accepted:true,current:true,authorized:true,conflict:false}],human_takeover:false,new_reply:false,previous_effect:'NOT_SUBMITTED',binding_qualified:true,notification_mode:'disabled',business_intent:'approved-operational',owner_policy_current:true,authority:{current:true,revoked:false,actor_id:'executor-a',department:'customer-service',operation_id:p.operation_id,action,recipient_id:p.recipient.id,organization_id:p.organization_id,purpose:p.purpose,resource_version:p.resource_version,payload_sha256:payloadDigest(p.payload)}};
 return {p,c};
}
for(const action of ['external-send','appointment-create','appointment-reschedule','appointment-cancel'])test(`eligible ${action} is only a delegated plan`,()=>{const {p,c}=fixture(action);const out=check(p,c);assert.equal(out.result,'ELIGIBLE_PLAN');assert.equal(out.executed,false);assert.equal(out.action,action==='external-send'?'communication.external.send':`appointment.${action.slice(12)}`);});
for(const department of ['sales','leasing','finance','ads','marketing','technology'])test(`${department} label cannot send externally`,()=>{const {p,c}=fixture();c.work_department=department;assert.equal(check(p,c).reason,'CUSTOMER_SERVICE_ONLY');});
const cases=[
 ['forged authentication',(_p,c)=>c.authenticated=false],['cross organization',(p)=>p.recipient.organization_id='other'],['unknown recipient',(p)=>p.recipient.classification='UNKNOWN'],['unverified recipient',(_p,c)=>c.recipient_verified=false],
 ['stale source',(_p,c)=>c.sources[0].current=false],['inference source',(_p,c)=>c.sources[0].accepted=false],['source conflict',(_p,c)=>c.sources[0].conflict=true],['unauthorized source',(_p,c)=>c.sources[0].authorized=false],['missing source',(_p,c)=>c.sources=[]],
 ['human takeover',(_p,c)=>c.human_takeover=true],['new reply',(_p,c)=>c.new_reply=true],['unknown prior effect',(_p,c)=>c.previous_effect='UNKNOWN'],['already submitted',(_p,c)=>c.previous_effect='SUCCEEDED'],['unqualified provider',(_p,c)=>c.binding_qualified=false],
 ['revoked authority',(_p,c)=>c.authority.revoked=true],['payload change',(p)=>p.payload.content='binding offer'],['recipient change',(p)=>p.recipient.id='other'],['purpose change',(p)=>p.purpose='negotiation'],['resource version change',(p)=>p.resource_version='4'],['operation change',(p)=>p.operation_id='new'],['actor change',(_p,c)=>c.actor_id='other'],['owner policy stale',(_p,c)=>c.owner_policy_current=false],['negotiation prohibited',(_p,c)=>c.business_intent='offer-transmission'],['missing authority',(_p,c)=>delete c.authority],['unknown takeover',(_p,c)=>delete c.human_takeover],['unknown prior effect',(_p,c)=>delete c.previous_effect]
];
for(const [label,mutate]of cases)test(`fail closed: ${label}`,()=>{const {p,c}=fixture();mutate(p,c);assert.equal(check(p,c).result,'BLOCKED');assert.equal(check(p,c).executed,false);});
test('provider default calendar notice cannot bypass contact boundary',()=>{const {p,c}=fixture('appointment-create');c.notification_mode='provider-default';assert.equal(check(p,c).reason,'COMPOUND_NOTIFICATION_BYPASS');});
test('no Finance/business mutation route',()=>{const {p,c}=fixture();p.action='finance.payment.execute';assert.equal(check(p,c).reason,'UNSUPPORTED_ACTION');});
test('missing inputs fail closed',()=>assert.equal(check(null,null).result,'BLOCKED'));
test('strict plan schema validates and rejects arbitrary actions/fields',()=>{const schema=JSON.parse(readFileSync(new URL('../skills/woia-customer-service/references/service-plan.schema.json',import.meta.url)));const validate=new Ajv().compile(schema);const {p}=fixture();assert.equal(validate(p),true);assert.equal(validate({...p,bypass:true}),false);assert.equal(validate({...p,action:'negotiate'}),false);});
test('Core hard minimum and immutable binding preserved',()=>{const m=JSON.parse(readFileSync(new URL('../dev.woia/manifest.json',import.meta.url)));assert.deepEqual(m.requires_plugins,[{name:'woia-core',minimum_version:'0.5.3'}]);assert.equal(m.core_binding.commit,'7a05b942bc244b385ea1403ed5dc975fdae22e24');assert.equal(m.department,'customer-service');});
test('missing payload and unknown plan fields reject without granting effects',()=>{const {p,c}=fixture();assert.equal(check({...p,payload:null},c).result,'BLOCKED');assert.equal(check({...p,bypass:true},c).result,'BLOCKED');});
